# Generated by Django 4.2.4 on 2023-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=300, null=True)),
                ('Item', models.CharField(blank=True, max_length=300, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
