# Generated by Django 4.1 on 2023-08-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='Total',
            new_name='total',
        ),
    ]
